
	CPU	6809

	INCLUDE	polyfill.asm							;;Needed for CLC, SEC, SEI, and CLI macros
	
	INCLUDE RRFRED.ASM							;;Referenced a lot, also includes RRF.ASM too

;	INCLUDE RRTABLE.ASM
;	INCLUDE RRX7.ASM
;	INCLUDE RRG23.ASM
;	INCLUDE RRB10.ASM
;	INCLUDE RRC11.ASM

	INCLUDE RRDX2.ASM
	INCLUDE RRLOG.ASM
	INCLUDE RRH11.ASM
	
;	INCLUDE RRTEST1.ASM
;	RRM1.ASM
;	RRP8.ASM
;	RRS22.ASM
;	RRSET.ASM

;	RRT2.ASM
;	RRTESTB.ASM 
;	RRTESTC.ASM
;	RRTEXT.ASM
;	RRTK4.ASM
;	RRELESE6.ASM